version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: global-payment-db
    environment:
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
      POSTGRES_DB: global_payment
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
