spring:
  application:
    name: global-payment-service

  # Database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/global_payment
    username: payment_user
    password: payment_password
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate settings
  jpa:
    hibernate:
      # Auto update schema under the development (in live environment should be 'none' with Liquibase/Flyway)
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Flyway config
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
