spring:
  application:
    name: global-payment-service

  # Database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/global_payment
    username: payment_user
    password: payment_password
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate settings
  jpa:
    hibernate:
      # Auto update schema under the development (in live environment should be 'none' with Liquibase/Flyway)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # Just in test task
  sql:
    init:
      mode: always

  # Flyway config
  flyway:
    enabled: false
    baseline-on-migrate: false

server:
  port: 8080
